title: Lakca's Notes

theme: jekyll-theme-cayman

plugins:
  - jekyll-github-metadata
  - jekyll-mermaid
  - jekyll-seo-tag

mermaid:
  src: /static/script/mermaid.min.js

timezone: Asia/Shanghai

github:
  show: false

show_downloads: false
excerpt_separator: <!--more-->

source: _posts

markdown: GFM

# https://github.com/gjtorikian/commonmarker#options
commonmark:
  options:
    - UNSAFE
    - SMART
    - FOOTNOTES
  extensions:
    - strikethrough
    - autolink
    - table
    - tagfilter
    - tasklist
    - superscript
    - header_ids
    - footnotes
    - description_lists
    - front_matter_delimiter
    - shortcodes

sass:
  sass_dir: assets/css
  style: compressed
