title: Lakca's Notes

theme: jekyll-theme-cayman

plugins:
  - jekyll-github-metadata
  - jekyll-mermaid
  - jekyll-seo-tag

mermaid:
  src: /static/script/mermaid.min.js

timezone: Asia/Shanghai

github:
  show: false

show_downloads: false
excerpt_separator: <!--more-->

source: _posts

markdown: GFM

sass:
  sass_dir: assets/css
  style: compressed
